"""empty message

Revision ID: 100e537ed66e
Revises: 
Create Date: 2023-09-19 19:58:16.148409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100e537ed66e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urllists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url_str', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('urllists')
    # ### end Alembic commands ###
